trigger:
  branches:
    include:
      - main  # Runs on every commit to main

pool:
  name: 'test1'  # Ensure this is your self-hosted agent pool

variables:
  azureServiceConnection: 'ml-rg-connect'  # Name of your Azure service connection
  location: 'South India'
  resourceGroupName: 'ml-rg'
  workspaceName: 'ml-workspace'

stages:
- stage: CheckAzureML
  displayName: 'Check Azure ML Resources'
  jobs:
  - job: CheckResources
    displayName: 'List Azure ML Resources'
    steps:
    - checkout: self  # Pulls code from repository

    - task: AzureCLI@2
      displayName: 'List Azure ML Resources'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Fetching Azure ML resources in resource group: $(resourceGroupName)"
          
          # List Azure ML Workspaces
          echo "Available ML Workspaces:"
          az ml workspace list --resource-group $(resourceGroupName) --output table
          
          # List Compute Instances
          echo "Available Compute Instances:"
          az ml compute list --resource-group $(resourceGroupName) --workspace-name $(workspaceName) --output table
          
          # List Datasets
          echo "Available Datasets:"
          az ml dataset list --resource-group $(resourceGroupName) --workspace-name $(workspaceName) --output table
          
          # List Models
          echo "Available Models:"
          az ml model list --resource-group $(resourceGroupName) --workspace-name $(workspaceName) --output table
