trigger:
  branches:
    include:
      - main  # Runs on every commit to main

pool:
  vmImage: 'Azure Pipelines'

variables:
  azureServiceConnection: 'ml-rg-connect'  # Name of your Azure service connection
  location: 'South India'
  resourceGroupName: 'ml-rg'
  workspaceName: 'ml-workspace'

stages:
- stage: CheckAzureML
  displayName: 'Check Azure ML Resources'
  jobs:
  - job: Deploy
    displayName: 'Deploy Bicep Template'
    steps:
    - checkout: self  # Pulls code from GitHub

    - task: AzureCLI@2
      displayName: 'Run Bicep Deployment'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az deployment group create \
            --resource-group $(resourceGroupName) \
            --template-file check-ml.bicep \
            --parameters location=$(location) workspaceName=$(workspaceName)
